#ifndef MODBUS_LESSON_SRC_ERRORCODE_H_
#define MODBUS_LESSON_SRC_ERRORCODE_H_

enum ErrorCode {
  SUCCESS = 0,
  INVALID_RESPONSE = 230,
  INVALID_REQUEST = 231,
  OPERATION_INTERRUPT = 255,
};
#endif //MODBUS_LESSON_SRC_ERRORCODE_H_
